Repository Energinet-DataHub/greenforce-frontend, pull requests merged in 2022-12, with the labels that each got.

#1181 feat(dh): use watt table in charges
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.spec.ts
  libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/details-header/dh-charge-details-header.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/dh-charge-content.component.spec.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/dh-charge-content.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/drawer-datepicker/dh-drawer-datepicker.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/history-tab/dh-charges-charge-history-tab.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/message-tab/dh-charges-charge-messages-tab.component.html
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/message-tab/dh-charges-charge-messages-tab.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/price-tab/dh-charges-charge-prices-tab.component.html
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/price-tab/dh-charges-charge-prices-tab.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/dh-charges-prices-drawer.component.html
  libs/dh/charges/feature-prices/src/lib/drawer/dh-charges-prices-drawer.component.ts
  libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.html
  libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.scss
  libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.ts
  libs/dh/charges/shell/src/lib/dh-charges-shell.module.ts
  libs/ui-watt/src/lib/components/table/index.ts
  libs/ui-watt/src/lib/components/table/watt-table.component.html
  libs/ui-watt/src/lib/components/table/watt-table.component.scss
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: Frontend, Design system (Watt), cla-signed

#1186 Remove rendering bug for paginator in Certificates page
  libs/eo/certificates/src/lib/eo-certificates-table.component.ts
Labels: cla-signed

#1193 fix: Missing import for permission.
  libs/dh/market-participant/feature-organization/src/lib/overview/dh-market-participant-organization-overview.component.ts
Labels: cla-signed

#1174 feat(watt): add support for selecting all options in dropdown
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.html
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.scss
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.ts
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.module.spec.ts
Labels: cla-signed

#1195 fix(ui-watt): minor watt-table fixes
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/table/+storybook/watt-table.stories.ts
  libs/ui-watt/src/lib/components/table/watt-table.component.scss
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: cla-signed

#1196 fix(ci): add environment variables to workflow
  .github/workflows/watt-cd.yml
Labels: cla-signed

#1194 fix(ui-watt): card background
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/card/watt-card.component.ts
Labels: cla-signed

#1198 Move FAQ into help and make empty pages behind flag
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/core/shell/src/lib/eo-core-shell.module.ts
  libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts
  libs/eo/faq/shell/README.md
  libs/eo/help/shell/.eslintrc.json
  libs/eo/help/shell/jest.config.ts
  libs/eo/help/shell/project.json
  libs/eo/help/shell/src/eo-help-shell.module.ts
  libs/eo/help/shell/src/index.ts
  libs/eo/help/shell/src/lib/eo-faq-page.component.ts
  libs/eo/help/shell/src/lib/eo-geography-page.component.ts
  libs/eo/help/shell/src/lib/eo-help-page.component.ts
  libs/eo/help/shell/src/lib/eo-introduction-page.component.ts
  libs/eo/help/shell/src/lib/eo-simultaneity-page.component.ts
  libs/eo/help/shell/src/test-setup.ts
  libs/eo/help/shell/tsconfig.json
  libs/eo/help/shell/tsconfig.lib.json
  libs/eo/help/shell/tsconfig.spec.json
  libs/eo/shared/services/src/feature-flag/feature-flag.service.ts
  libs/eo/shared/utilities/src/lib/eo-routes.ts
  tsconfig.base.json
  workspace.json
Labels: cla-signed

#1199 adding permission required organizations
  libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
  libs/dh/market-participant/feature-organization/src/lib/dh-market-participant-organization.component.html
  libs/dh/market-participant/feature-organization/src/lib/dh-market-participant-organization.component.ts
  libs/dh/market-participant/feature-organization/src/lib/overview/dh-market-participant-organization-overview.component.html
  libs/dh/market-participant/shell/src/lib/dh-market-participant-shell.module.ts
Labels: cla-signed

#1201 chore: update Angular to latest v14
  PRODUCTION_DEPENDENCIES.md
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  package.json
  yarn.lock
Labels: cla-signed

#1202 Notify team if deployment dispatch failed
  .github/workflows/dh-cd.yml
  .github/workflows/dh-ci.yml
  .github/workflows/watt-cd.yml
Labels: cla-signed

#1207 feat(dh): use watt-table in wholesale
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.html
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.ts
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.html
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts
  libs/ui-watt/src/lib/components/table/watt-table.component.html
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: cla-signed

#1210 reafc: processStepResultDto in ActionResult
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/Wholesale/Dto/BatchDto.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleBatchController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/wholesale-batch-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/batch-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/process-step-metering-point-type.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/process-step-result-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/time-series-point-dto.ts
  libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.html
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.html
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.html
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts
Labels: cla-signed

#1209 Add user role template client.
  apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantControllerBase.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleTemplateController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api.module.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/api.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-template-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-template-dto.ts
Labels: cla-signed

#1203 feat: Help pages
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts
  libs/eo/help/shell/src/eo-help-shell.module.ts
  libs/eo/help/shell/src/lib/eo-geography-page.component.ts
  libs/eo/help/shell/src/lib/eo-help-page.component.ts
  libs/eo/help/shell/src/lib/eo-introduction-page.component.ts
  libs/eo/help/shell/src/lib/eo-simultaneity-page.component.ts
  libs/eo/shared/assets/src/assets/images/help/case_geography.jpg
  libs/eo/shared/assets/src/assets/images/help/goal_7.png
  libs/eo/shared/assets/src/assets/images/help/hour_declaration.png
  libs/eo/shared/assets/src/assets/images/help/ivan_case.jpg
  libs/eo/shared/assets/src/assets/images/help/law_paragraph.png
  libs/eo/shared/assets/src/assets/images/help/map_geography.jpg
  libs/eo/shared/assets/src/assets/images/help/move_consumption.png
  libs/eo/shared/assets/src/assets/images/help/power_to_x.png
  libs/eo/shared/atomic-design/ui-atoms/src/index.ts
  libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-info-box/eo-info-box.component.ts
  libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-media/eo-media.module.ts
Labels: cla-signed

#1180 Added mock
  libs/dh/shared/data-access-msw/src/lib/mocks/data/messageArchiveSearchResponseLogs.json
  libs/dh/shared/data-access-msw/src/lib/mocks/messageArchive.ts
Labels: cla-signed

#1220 fix(watt): fix change detection error
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/tabs/index.ts
  libs/ui-watt/src/lib/components/tabs/tab/tab.component.html
  libs/ui-watt/src/lib/components/tabs/watt-tab.component.ts
  libs/ui-watt/src/lib/components/tabs/watt-tabs.component.html
  libs/ui-watt/src/lib/components/tabs/watt-tabs.component.scss
  libs/ui-watt/src/lib/components/tabs/watt-tabs.component.ts
  libs/ui-watt/src/lib/components/tabs/watt-tabs.module.ts
Labels: cla-signed

#1223 Limit width on help pages
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/help/shell/src/lib/eo-geography-page.component.ts
  libs/eo/help/shell/src/lib/eo-introduction-page.component.ts
  libs/eo/help/shell/src/lib/eo-simultaneity-page.component.ts
Labels: cla-signed

#1222 chore: bumped markpart client package
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/model/user-overview-item-dto.ts
Labels: cla-signed

#1224 feat(dh): update store to get users data
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/dh-users-tab.component.ts
  libs/dh/shared/data-access-msw/src/lib/handlers.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserOverview.json
Labels: cla-signed

#1225 refactor: dh message archive as standalone
  libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/shared/dh-message-archive-status.component.ts
  libs/dh/message-archive/shell/src/lib/dh-message-archive-shell.module.ts
Labels: cla-signed

#1221 Add controller for user role assigment
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleAssignmentController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api.module.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/api.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-assignment-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/update-user-role-assignments-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-template-id-dto.ts
Labels: cla-signed

#1226 feat(ui-watt): add large size to watt-badge
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.ts
  libs/dh/market-participant/feature-gridarea/src/lib/overview/dh-market-participant-gridarea-overview.component.ts
  libs/dh/market-participant/feature-organization/src/lib/overview/dh-market-participant-organization-overview.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/shared/dh-message-archive-status.component.ts
  libs/dh/metering-point/ui-status-badge/src/lib/dh-metering-point-status-badge.component.ts
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.ts
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts
  libs/ui-watt/src/lib/components/badge/+storybook/badge.stories.ts
  libs/ui-watt/src/lib/components/badge/badge.component.html
  libs/ui-watt/src/lib/components/badge/badge.module.ts
  libs/ui-watt/src/lib/components/badge/index.ts
  libs/ui-watt/src/lib/components/badge/watt-badge.component.scss
  libs/ui-watt/src/lib/components/badge/watt-badge.component.ts
  libs/ui-watt/src/lib/components/badge/watt-badge.stories.ts
  libs/ui-watt/src/lib/components/expandable-card/watt-expandable-card.component.scss
  libs/ui-watt/src/lib/components/expandable-card/watt-expandable-card.stories.ts
  libs/ui-watt/src/lib/foundations/typography/_typography.import.scss
Labels: 🏗️ Platform, ⚡ Watt, cla-signed

#1228 feat(dh): add table to users tab
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1234 feat(watt): dropdown model should update continuously
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.ts
Labels: cla-signed

#1230 fix: No permission for multiple users.
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/TokenController.cs
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/token-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/feature-authorization/src/lib/actor-token.service.spec.ts
  libs/dh/shared/feature-authorization/src/lib/actor-token.service.ts
  libs/dh/shared/feature-authorization/src/lib/dh-authorization.interceptor.ts
  libs/dh/shared/feature-authorization/src/lib/permission.service.spec.ts
  libs/dh/shared/feature-authorization/src/lib/permission.service.ts
Labels: cla-signed

#1200 refac: Use JWT permission middleware.
  libs/dh/auth/feature-msal/src/lib/b2c-config.ts
  libs/dh/shared/feature-authorization/src/lib/dh-authorization.interceptor.ts
  libs/dh/shared/feature-authorization/src/lib/permission.service.spec.ts
  libs/dh/shared/feature-authorization/src/lib/permission.service.ts
  libs/dh/shared/feature-flags/src/lib/feature-flags.ts
Labels: cla-signed

#1239 fix: add missing mocks
  libs/dh/shared/data-access-msw/src/lib/handlers.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipantUser.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/token.ts
Labels: cla-signed

#1238 Feat/block failed batch
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.ts
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.html
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.html
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.ts
  libs/ui-watt/src/lib/components/table/watt-table.component.html
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: cla-signed

#1241 Add new endpoint to BFF to get actors to a userId
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-http.service.ts
Labels: cla-signed

#1229 fix(ui-watt): use ChangeDetectionStrategy.Default in watt-table
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: cla-signed

#1243 feat(dh): only import DhSharedUtilApplicationInsightsModule in production
  libs/dh/core/shell/src/lib/dh-core-shell.module.ts
Labels: cla-signed

#1232 Bug/revert back grid size on help
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/emissions/shell/src/lib/eo-emissions-page-shell.component.ts
  libs/eo/help/shell/src/eo-help-shell.module.ts
  libs/eo/help/shell/src/lib/eo-geography-page.component.ts
  libs/eo/help/shell/src/lib/eo-introduction-page.component.ts
  libs/eo/help/shell/src/lib/eo-simultaneity-page.component.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.component.ts
Labels: cla-signed

#1244 feat(wholesale): add new grid areas
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts
Labels: cla-signed

#1245 feat(dh): add page number and page size as params to request
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1246 feat(wholesale): add grid area 351
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts
Labels: cla-signed

#1248 Remove organization view permission.
  libs/dh/core/shell/src/lib/dh-primary-navigation.component.html
  libs/dh/market-participant/feature-gridarea/src/lib/details-auditlog/dh-market-participant-gridarea-details-auditlog.component.html
  libs/dh/market-participant/feature-gridarea/src/lib/details-auditlog/dh-market-participant-gridarea-details-auditlog.component.ts
  libs/dh/market-participant/feature-gridarea/src/lib/details-edit/dh-market-participant-gridarea-edit.component.html
  libs/dh/market-participant/feature-gridarea/src/lib/details-edit/dh-market-participant-gridarea-edit.component.ts
  libs/dh/market-participant/shell/src/lib/dh-market-participant-shell.module.ts
  libs/dh/shared/feature-authorization/src/lib/permission.guard.spec.ts
  libs/dh/shared/feature-authorization/src/lib/permission.service.spec.ts
  libs/dh/shared/feature-authorization/src/lib/permission.ts
Labels: cla-signed

#1250 fix(mocks): adjust token mock
  apps/dh/app-dh/project.json
  libs/dh/shared/data-access-msw/src/lib/mocks/token.ts
  libs/dh/shared/domain/src/index.ts
  libs/dh/shared/domain/src/lib/permission.ts
  libs/dh/shared/feature-authorization/src/index.ts
  libs/dh/shared/feature-authorization/src/lib/permission-required.directive.ts
  libs/dh/shared/feature-authorization/src/lib/permission.guard.ts
  libs/dh/shared/feature-authorization/src/lib/permission.service.ts
  libs/dh/shared/feature-flags/src/lib/feature-flags.ts
  package.json
  yarn.lock
Labels: cla-signed

#1253 fix(wholesale): remove redundant usage of query params in mocks
  libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
Labels: cla-signed

#1252 Update BFF API.
  .github/workflows/frontend-ci.yml
  apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleAssignmentController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-assignment-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
Labels: cla-signed

#1254 fix(watt): make sure getCellData won't fail if column is undefined (watt-table)
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: cla-signed

#1255 feat(dh): add type to Output property
  libs/dh/shared/ui-paginator/src/lib/dh-shared-ui-paginator.component.ts
Labels: cla-signed

#1256 Add optional header input to wattTableCellDirective
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: cla-signed

#1249 feat(wholesale): add data to process step result drawer
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/25-production-per-gridarea.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/25-production-per-gridarea.component.scss
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/25-production-per-gridarea.component.ts
Labels: cla-signed

#1257 fix(wholesale): reset selected batch on search
  libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts
Labels: 🐞 Bug, cla-signed

#1258 fix(dh): show users list in user management page
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserOverviewController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-container.component.html
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab-container.component.ts
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/user-management-tabs/users-tab/dh-users-tab.component.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserOverview.json
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-overview-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-overview-result-dto.ts
Labels: cla-signed

#1233 feat(wholesale): add loading and error states
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
  libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.scss
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.scss
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.ts
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.html
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.scss
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.ts
  libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.html
  libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts
Labels: cla-signed

#1260 chore: Update BFF.
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleAssignmentController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-assignment-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/update-user-role-assignments-dto.ts
Labels: cla-signed

#1247 fix: Improve cache of token.
  libs/dh/shared/feature-authorization/src/lib/actor-token.service.ts
Labels: cla-signed
