Repository Energinet-DataHub/greenforce-frontend, pull requests merged in 2023-01, with the labels that each got.

#1259 refac: Update markpart to use RPC API.
  apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantActorQueryController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantGridAreaController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantGridAreaOverviewController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserOverviewController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleAssignmentController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-data-access-api.store.ts
  libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-edit-actor-data-access-api.store.ts
  libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-edit-organization-data-access-api.store.ts
  libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-gridarea-data-access-api.store.ts
  libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-gridareaoverview-data-access-api.store.ts
  libs/dh/message-archive/data-access-api/src/lib/dh-message-archive-actor-data-access-api.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipant.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipantUser.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-actor-query-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-grid-area-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-grid-area-overview-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-overview-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-assignment-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
  libs/dh/shared/feature-authorization/src/lib/actor-token.service.spec.ts
  libs/dh/shared/feature-authorization/src/lib/actor-token.service.ts
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.store.ts
Labels: cla-signed

#1270 feat: Add API for user audit log.
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserController.cs
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-audit-logs-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-assignment-audit-log-entry.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-assignment-type-audit-log.ts
Labels: cla-signed

#1271 refactor(dh): rename user management files
  libs/dh/admin/feature-user-management/src/lib/dh-admin-feature-user-management.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-container.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-container.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.scss
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/general-error/dh-users-tab-general-error.component.ts
Labels: cla-signed

#1272 feat(dh): add status badge to user management page
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-user-status.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1263 feat(ui-watt): watt paginator
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/globalization/ui-watt-translation/src/lib/dh-globalization-ui-watt-translation.module.ts
  libs/ui-watt/src/lib/components/input/shared/watt-input-mask.service.ts
  libs/ui-watt/src/lib/components/paginator/index.ts
  libs/ui-watt/src/lib/components/paginator/watt-paginator-intl.service.ts
  libs/ui-watt/src/lib/components/paginator/watt-paginator.component.scss
  libs/ui-watt/src/lib/components/paginator/watt-paginator.component.ts
  libs/ui-watt/src/lib/components/table/+storybook/storybook-table-decorator.component.ts
  libs/ui-watt/src/lib/components/table/watt-table-data-source.ts
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
  libs/ui-watt/src/lib/foundations/_table.scss
  tsconfig.base.json
Labels: cla-signed

#1274 Update package and generate API for audit log.
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipant/Dto/UserAuditLogsDto.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipant/Dto/UserRoleAssignmentAuditLogDto.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleAssignmentController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-audit-logs-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-assignment-audit-log-dto.ts
Labels: cla-signed

#1278 feat(dh): remove old health check calls
  apps/dh/api-dh/source/DataHub.WebApi/Registration/HealthEndpointRegistrationExtensions.cs
Labels: cla-signed

#1277 bff update user roles get all
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-info-dto.ts
Labels: cla-signed

#1275 feat: switch actor (frontend)
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/model/selection-actor-dto.ts
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.html
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.scss
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.ts
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.store.ts
  libs/dh/shared/feature-authorization/src/lib/window-location.ts
Labels: cla-signed

#1280 fix: correct actor name in actor selector
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.store.ts
Labels: cla-signed

#1282 chore: standalone the master data overview components
  libs/dh/metering-point/feature-overview/src/lib/breadcrumb/dh-breadcrumb.component.ts
  libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-feature-overview.module.ts
  libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
  libs/dh/metering-point/feature-overview/src/lib/general-error/dh-metering-point-general-error.component.ts
  libs/dh/metering-point/feature-overview/src/lib/not-found/dh-metering-point-not-found.component.ts
Labels: cla-signed

#1283 chore(ui-watt): change label color from primary-dark -> neutral-black
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/foundations/_variables.scss
Labels: ⚡ Watt, cla-signed

#1284 chore:(ui-watt): remove size option from button
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/metering-point/feature-search/src/lib/form/dh-metering-point-search-form.component.html
  libs/ui-watt/src/lib/components/button/+storybook/storybook-button-overview.component.html
  libs/ui-watt/src/lib/components/button/watt-button.component.scss
  libs/ui-watt/src/lib/components/button/watt-button.component.spec.ts
  libs/ui-watt/src/lib/components/button/watt-button.component.ts
Labels: ⚡ Watt, cla-signed

#1235 Feat/884 drawer user roles
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/tabs/content/dh-user-master-data.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/tabs/content/dh-user-master-data.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/tabs/dh-drawer-tabs.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/tabs/dh-drawer-tabs.component.ts
  libs/dh/admin/feature-user-management/src/lib/shared/dh-user-status.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.ts
Labels: cla-signed

#1286 chore: remove B-001 and B-002 environments
  README.md
  apps/dh/e2e-dh/src/integration/b2c.spec.ts
  docs/dh/datahub-bookmarks.html
  libs/dh/shared/environments/src/lib/app-environment/dh-app-environment.ts
  libs/dh/shared/feature-flags/src/lib/feature-flag.directive.spec.ts
  libs/dh/shared/feature-flags/src/lib/feature-flags.service.spec.ts
  libs/dh/shared/feature-flags/src/lib/feature-flags.service.ts
  libs/dh/shared/feature-flags/src/lib/feature-flags.ts
Labels: cla-signed

#1288 Remove Azure deployment of Watt
  .github/workflows/watt-cd.yml
  .github/workflows/watt-ci.yml
Labels: cla-signed

#1261 Conditional add project reference if exists, to make a poor man monor…
  .gitignore
  .vscode/launch.json
  .vscode/tasks.json
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  backend/readme.md
Labels: cla-signed

#1292 feat: selected actor spinner
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.html
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.scss
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.ts
Labels: cla-signed

#1287 Add toast when starting new batch
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.html
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.scss
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.spec.ts
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts
Labels: cla-signed

#1281 feat(dh): show spinner when lazy loading pages in table
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-container.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-container.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.scss
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1300 feat(watt): make it possible to disable the dropdown
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.html
  libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-reactive-forms.stories.ts
  libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-template-driven-forms.stories.ts
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.html
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.ts
Labels: ⚡ Watt, cla-signed

#1306 change name of mighty ducks
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-reactive-forms.stories.ts
  libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-template-driven-forms.stories.ts
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.module.spec.ts
Labels: cla-signed

#1305 feat(dh): implement user search
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-search.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.spec.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1314 Do not display anything when user filter is empty.
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
Labels: cla-signed

#1304 user roles list filter and refactor
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/dh-tabs.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-container.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-list-filter.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-list-filter.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.scss
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1317 feat(dh): add unit tests to user management
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.spec.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.spec.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserOverview.json
Labels: cla-signed

#1318 userroleid param fix
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-permissions-management-data-access-api.store.ts
Labels: cla-signed

#1319 refactor(dh): use Watt table in users tab
  libs/dh/admin/data-access-api/src/index.ts
  libs/dh/admin/data-access-api/src/lib/dh-custom-data-source.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.spec.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
Labels: cla-signed

#1320 chore: update RxAngular
  PRODUCTION_DEPENDENCIES.md
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/tabs/content/dh-user-audit-logs.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-list-filter.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
  libs/dh/charges/feature-create-prices/src/lib/dh-charges-create-prices.component.ts
  libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/message-tab/dh-charges-charge-messages-tab.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-content/price-tab/dh-charges-charge-prices-tab.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/charge-message/dh-charge-price-message.component.ts
  libs/dh/charges/feature-prices/src/lib/drawer/dh-charges-prices-drawer.component.ts
  libs/dh/charges/feature-prices/src/lib/search-result/dh-charges-prices-result.component.ts
  libs/dh/core/shell/src/lib/dh-core-shell.component.ts
  libs/dh/globalization/feature-language-picker/src/lib/language-picker/dh-language-picker.module.ts
  libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/dh-market-participant-edit-actor.component.ts
  libs/dh/market-participant/feature-gridarea/src/lib/dh-market-participant-gridarea.component.ts
  libs/dh/market-participant/feature-organization/src/lib/dh-market-participant-organization.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/dh-message-archive-log-search.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/drawer/dh-message-archive-drawer.component.ts
  libs/dh/message-archive/feature-log-search/src/lib/searchresult/dh-message-archive-log-search-result.component.ts
  libs/dh/metering-point/feature-identity-and-master-data/src/lib/dh-metering-point-identity-and-master-data.component.ts
  libs/dh/metering-point/feature-overview/src/lib/dh-metering-point-overview.component.ts
  libs/dh/metering-point/feature-search/src/lib/dh-metering-point-search.component.ts
  libs/dh/metering-point/feature-tabs/src/lib/charges-tab-content/dh-charges-tab-content.component.ts
  libs/dh/metering-point/feature-tabs/src/lib/dh-metering-point-tabs.component.ts
  libs/dh/metering-point/feature-tabs/src/lib/processes-tab-content/dh-processes-tab-content.component.ts
  libs/dh/shared/feature-authorization/src/lib/dh-selected-actor.component.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.ts
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.html
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.ts
  libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.html
  libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts
  libs/eo/certificates/src/lib/certificate-details/eo-certificate-details.component.ts
  libs/eo/consumption-page/shell/src/lib/eo-consumption-chart-card.component.ts
  libs/eo/consumption-page/shell/src/lib/eo-consumption-page-shell.component.ts
  libs/eo/core/shell/src/lib/eo-shell.component.ts
  libs/eo/emissions/shell/src/lib/eo-emissions-page-shell.component.ts
  libs/eo/landing-page/shell/src/lib/eo-landing-page-login-button.component.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-points-shell.component.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-pie-chart.component.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.component.ts
  libs/eo/production/shell/src/lib/eo-production-chart-card.component.ts
  libs/eo/production/shell/src/lib/eo-production-shell.component.ts
  libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-privacy-policy/eo-privacy-policy.component.ts
  libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-media/eo-media.component.ts
  libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-resolution-picker/eo-resolution-picker.component.ts
  libs/ui-watt/src/lib/components/drawer/+storybook/storybook-drawer-loading.component.ts
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.module.ts
  package.json
  yarn.lock
Labels: cla-signed

#1321 refactor(ui-watt): change layout of text-field
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/input/+storybook/input.directive.stories.ts
  libs/ui-watt/src/lib/components/input/+storybook/storybook-input-overview.component.html
  libs/ui-watt/src/lib/components/input/+storybook/storybook-input-overview.component.scss
  libs/ui-watt/src/lib/components/input/+storybook/storybook-input-overview.mdx
  libs/ui-watt/src/lib/components/input/+storybook/storybook-input-wrapper.component.ts
Labels: ⚡ Watt, cla-signed

#1323 docs: add liveshare to recommendations
  .vscode/extensions.json
Labels: cla-signed

#1326 feat(dh): add endpoint mock
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetAll.json
Labels: cla-signed

#1327 feat(dh): add endpoint mock
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserGetUserAuditLogs.json
Labels: cla-signed

#1331 feat(dh): highlight table row and mock endpoint
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
Labels: cla-signed

#1332 chore: update dependencies
  PRODUCTION_DEPENDENCIES.md
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  package.json
  yarn.lock
Labels: cla-signed

#1334 bff update for user role auditlogs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipant/Dto/UserRoleAuditLogDto.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipant/Dto/UserRoleAuditLogsDto.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-audit-log-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-audit-logs-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-change-type.ts
Labels: cla-signed

#1330 Update secrets used in automated tests
  .github/workflows/dh-cd.yml
  .github/workflows/dh-ci.yml
  apps/dh/api-dh/source/DataHub.WebApi.Tests/DataHub.WebApi.Tests.csproj
  apps/dh/api-dh/source/DataHub.WebApi.Tests/integrationtest.local.settings.sample.json
Labels: cla-signed

#1336 chore(dh): restructure localization
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-permissions.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1337 fix: set version on license-checker-rseidelsohn package
  .github/workflows/production-dependencies-license-check.yml
Labels: 🏗️ Platform, cla-signed

#1339 feat(dh): implement roles audit log
  libs/dh/admin/data-access-api/src/index.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-audit-logs-data-access-api.store.spec.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-audit-logs-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-audit-logs.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-audit-logs.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/dh-drawer-role-tabs.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleAuditLogs.json
Labels: cla-signed

#1338 feat(style): add min height to toast
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/toast/watt-toast.component.scss
Labels: ⚡ Watt, cla-signed

#1344 Added modal with tap component on edit user
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.scss
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.spec.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-user-drawer.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1345 ref(style): Align dropdown
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.scss
Labels: ⚡ Watt, cla-signed

#1328 Activate GC on MP
  apps/eo/app-eo/project.json
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/certificates/src/eo-certificates.module.ts
  libs/eo/certificates/src/index.ts
  libs/eo/certificates/src/lib/eo-certificates-table.component.ts
  libs/eo/certificates/src/lib/eo-certificates.service.spec.ts
  libs/eo/certificates/src/lib/eo-certificates.service.ts
  libs/eo/certificates/src/test-setup.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-point-list.component.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-point-table.component.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-points-shell.component.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-points.service.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
  libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-popup-message/eo-popup-message.component.ts
  libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-idle-timer/idle-timer-countdown.component.ts
  libs/eo/shared/atomic-design/ui-atoms/src/lib/eo-idle-timer/idle-timer-logged-out.component.ts
Labels: cla-signed

#1348 Bug: Make contracts conditional
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/metering-points/shell/src/lib/eo-metering-points.store.ts
Labels: cla-signed

#1349 feat: Added created column to users.
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-list-filter.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1350 feat(dh): show user role audit logs in table
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-audit-logs-data-access-api.store.spec.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-audit-logs-data-access-api.store.ts
  libs/dh/admin/data-access-api/src/lib/util/map-change-description-json.spec.ts
  libs/dh/admin/data-access-api/src/lib/util/map-change-description-json.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-audit-logs.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-audit-logs.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleAuditLogs.json
Labels: cla-signed

#1352 feat: download user roles as csv
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.scss
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1353 adding endpoint for update user role
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/update-user-role-dto.ts
Labels: cla-signed

#1354 chore: bump markpart package
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/model/eic-function.ts
Labels: cla-signed

#1347 ref(style): adjust color breadcrumb
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/breadcrumbs/watt-breadcrumbs.component.scss
Labels: ⚡ Watt, cla-signed

#1357 feat: market role translations
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-master-data.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-master-data.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-list-filter.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1360 fix: user role export matches sort in table
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1361 feat(dh): edit user role modal
  libs/dh/admin/feature-edit-user-role-modal/.eslintrc.json
  libs/dh/admin/feature-edit-user-role-modal/README.md
  libs/dh/admin/feature-edit-user-role-modal/jest.config.ts
  libs/dh/admin/feature-edit-user-role-modal/project.json
  libs/dh/admin/feature-edit-user-role-modal/src/index.ts
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/admin/feature-edit-user-role-modal/src/test-setup.ts
  libs/dh/admin/feature-edit-user-role-modal/tsconfig.json
  libs/dh/admin/feature-edit-user-role-modal/tsconfig.lib.json
  libs/dh/admin/feature-edit-user-role-modal/tsconfig.spec.json
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  tsconfig.base.json
  workspace.json
Labels: cla-signed

#1355 Feat/wholesale restrict datepicker
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.html
  libs/dh/wholesale/feature-start/src/lib/dh-wholesale-start.component.ts
  libs/ui-watt/src/lib/components/input/datepicker/watt-datepicker.component.html
  libs/ui-watt/src/lib/components/input/datepicker/watt-datepicker.component.ts
Labels: cla-signed

#1362 Fixes after UX review
  libs/dh/admin/feature-user-management/src/lib/drawer/tabs/content/dh-user-roles.component.spec.ts
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/dh-create-userrole-tabs.component.html
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1363 Put a disclaimer on certificate details page
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/certificates/src/lib/certificate-details/eo-certificate-details.component.ts
Labels: cla-signed

#1366 feat: Add Actor column to user list.
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1365 Remove certificates feature flag
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/certificates/src/lib/eo-certificates-table.component.ts
  libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-point-table.component.ts
  libs/eo/shared/services/src/feature-flag/feature-flag.service.ts
Labels: cla-signed

#1367 Change language on error message
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-popup-message/eo-popup-message.component.ts
Labels: cla-signed

#1370 chore: Update BFF with new client package.
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserOverviewController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-overview-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-overview-filter-dto.ts
Labels: cla-signed
