Repository Energinet-DataHub/greenforce-frontend, pull requests merged in 2023-02, with the labels that each got.

#1373 Filter for actor name and user roles
  libs/dh/admin/data-access-api/src/index.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-actors-data-access-api.store.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.spec.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles-management-data-access-api.store.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles.store.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-actor-filter.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-userrole-filter.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1368 feat: users serverside sort when paging
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserOverviewController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.spec.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-overview-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/sort-direction.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-overview-sort-property.ts
Labels: cla-signed

#1376 Add API for filling out actor filters.
  apps/dh/api-dh/source/DataHub.WebApi.Tests/Fixtures/BffWebApiFixture.cs
  apps/dh/api-dh/source/DataHub.WebApi.Tests/Fixtures/IServiceMock.cs
  apps/dh/api-dh/source/DataHub.WebApi.Tests/Fixtures/WebApiFactory.cs
  apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/Controllers/MarketParticipantControllerTests.cs
  apps/dh/api-dh/source/DataHub.WebApi.Tests/ServiceMocks/JwtAuthenticationServiceMock.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/HttpContextUserExtensions.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Startup.cs
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-actors-data-access-api.store.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-http.service.ts
Labels: cla-signed

#1378 feat: Only show filter when there are multiple items.
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-actors-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
Labels: cla-signed

#1371 refactor: align buttons on edit user modal to reflect design
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.ts
  libs/ui-watt/src/lib/components/modal/watt-modal.component.scss
Labels: cla-signed

#1379 marketparticipant client nuget update
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserOverviewController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-permissions.component.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-overview-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-with-permissions-dto.ts
Labels: cla-signed

#1381 chore(dh): fix mock
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserSearchUsers.json
Labels: cla-signed

#1377 feat(dh): implement user role name edit in modal
  libs/dh/admin/data-access-api/src/index.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-permissions-management-data-access-api.store.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles-management-data-access-api.store.ts
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.html
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.scss
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/dh-role-drawer.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/roles-tab/dh-roles-tab-table.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/admin.ts
Labels: cla-signed

#1383 experiment(dh): graphql daterange
  apps/dh/api-dh/source/DataHub.WebApi/GraphQL/GraphQLQuery.cs
  apps/dh/api-dh/source/DataHub.WebApi/GraphQL/GraphQLSchema.cs
  apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Query/MarketParticipantQuery.cs
  apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/BatchType.cs
  apps/dh/api-dh/source/DataHub.WebApi/GraphQL/Types/DateRangeType.cs
  apps/dh/api-dh/source/DataHub.WebApi/Registration/GraphQLRegistrationExtensions.cs
  apps/dh/api-dh/source/DataHub.WebApi/Startup.cs
Labels: cla-signed

#1385 fix(wholesale): change type to TimeSeriesType.NonProfiledConsumption
  libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts
Labels: cla-signed

#1375 Bug in terms acceptance
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/auth/data-access-api/src/lib/auth-http.service.spec.ts
  libs/eo/auth/data-access-api/src/lib/auth-http.service.ts
  libs/eo/auth/feature-terms/project.json
  libs/eo/auth/feature-terms/src/lib/browser-location.token.ts
  libs/eo/auth/feature-terms/src/lib/eo-auth-terms.store.ts
  libs/eo/consumption-page/shell/src/lib/eo-consumption-page-shell.component.ts
  libs/eo/core/shell/src/lib/eo-core-shell.module.ts
  libs/eo/emissions/shell/src/lib/eo-emissions-page-shell.component.ts
  libs/eo/landing-page/shell/src/lib/eo-landing-page-shell.component.ts
  libs/eo/metering-points/shell/src/lib/eo-metering-points-shell.component.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy-shell.component.ts
  libs/eo/production/shell/src/lib/eo-production-shell.component.ts
  libs/eo/shared/atomic-design/feature-molecules/src/lib/eo-popup-message/eo-popup-message.component.ts
  libs/eo/shared/services/tsconfig.json
  libs/eo/shared/services/tsconfig.lib.json
  libs/eo/terms/.browserslistrc
  libs/eo/terms/.eslintrc.json
  libs/eo/terms/README.md
  libs/eo/terms/jest.config.ts
  libs/eo/terms/project.json
  libs/eo/terms/src/index.ts
  libs/eo/terms/src/lib/eo-terms.component.ts
  libs/eo/terms/src/lib/eo-terms.module.ts
  libs/eo/terms/src/lib/eo-terms.service.ts
  libs/eo/terms/src/lib/eo-terms.store.spec.ts
  libs/eo/terms/src/lib/eo-terms.store.ts
  libs/eo/terms/src/test-setup.ts
  libs/eo/terms/tsconfig.json
  libs/eo/terms/tsconfig.lib.json
  libs/eo/terms/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: cla-signed

#1382 Fix race condition bug on certs table
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/certificates/src/lib/eo-certificates-table.component.ts
Labels: cla-signed

#1388 Cleanup after terms move
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/auth/feature-terms/src/lib/browser-location.token.ts
Labels: cla-signed

#1389 Remove unneeded links
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/core/shell/src/lib/eo-primary-navigation.component.ts
  libs/eo/dashboard/shell/src/lib/eo-dashboard-get-data.component.ts
Labels: cla-signed

#1394 Added invite user modal
  libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.html
  libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.scss
  libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.ts
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
Labels: cla-signed

#1392 chore: unused market roles removed
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/create-role-masterdata-tab/dh-create-userrole-masterdata-tab.component.ts
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/dh-create-userrole-tabs.component.ts
  libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/dh-market-participant-actor-market-roles.component.spec.ts
  libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/market-role-group.service.spec.ts
  libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/market-role-group.service.ts
  libs/dh/market-participant/feature-edit-actor/src/lib/market-participant-edit-actor/market-roles/market-role.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/eic-function.ts
Labels: cla-signed

#1393 feat(watt): add support for setting form id on button component
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/button/watt-button.component.spec.ts
  libs/ui-watt/src/lib/components/button/watt-button.component.ts
Labels: cla-signed

#1395 feat(dh): add support for editing of user role description
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
Labels: cla-signed

#1396 chore(dh): adjust tests, mock data and typing
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-audit-logs-data-access-api.store.spec.ts
  libs/dh/admin/data-access-api/src/lib/util/map-change-description-json.spec.ts
  libs/dh/admin/data-access-api/src/lib/util/map-change-description-json.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleAuditLogs.json
Labels: cla-signed

#1398 feat(dh): display validation error message when user role name exists
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-api/src/lib/states.ts
Labels: cla-signed

#1399 test(dh): fix missing enum value
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-roles.store.spec.ts
Labels: cla-signed

#1400 Removed chars
  libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.html
  libs/dh/admin/feature-user-management/src/lib/invite-user-modal/dh-invite-user-modal.component.scss
Labels: cla-signed

#1402 feat(dh): make description field in edit user role required
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1404 fix(dh): use correct error property
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
Labels: cla-signed

#1302 Revert "feat(watt): make it possible to disable the dropdown"
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/charges/feature-prices/src/lib/dh-charges-prices.component.html
  libs/ui-watt/src/lib/components/dropdown/+storybook/storybook-dropdown-template-driven-forms.stories.ts
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.html
  libs/ui-watt/src/lib/components/dropdown/watt-dropdown.component.ts
Labels: cla-signed

#1403 feat(watt): add description list component
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/description-list/index.ts
  libs/ui-watt/src/lib/components/description-list/watt-description-list-term.ts
  libs/ui-watt/src/lib/components/description-list/watt-description-list.component.html
  libs/ui-watt/src/lib/components/description-list/watt-description-list.component.scss
  libs/ui-watt/src/lib/components/description-list/watt-description-list.component.spec.ts
  libs/ui-watt/src/lib/components/description-list/watt-description-list.component.ts
  libs/ui-watt/src/lib/components/description-list/watt-description-list.stories.ts
  tsconfig.base.json
Labels: cla-signed

#1407 feat(dh): show notification on success/error
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-role-edit-data-access-api.store.ts
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1405 Add function to limit permissions to selected eic function
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/admin/data-access-api/src/lib/dh-admin-create-user-role-management-data-access-api.store.ts
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/create-role-masterdata-tab/dh-create-userrole-masterdata-tab.component.ts
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab-table.component.html
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab-table.component.ts
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.html
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.scss
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.ts
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/dh-create-userrole-tabs.component.html
  libs/dh/admin/feature-user-management/src/lib/feature-create-userrole/tabs/dh-create-userrole-tabs.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRolePermissions.json
  libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipantUserRole.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
Labels: cla-signed

#1408 feat: organization domain - frontend org domain field
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/TokenController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  apps/dh/api-dh/source/DataHub.WebApi/Registration/DomainRegistrationExtensions.cs
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/market-participant/data-access-api/src/lib/dh-market-participant-edit-organization-data-access-api.store.ts
  libs/dh/market-participant/feature-edit-organization/src/lib/market-participant-edit-organization/master-data/dh-market-participant-organization-master-data.component.html
  libs/dh/market-participant/feature-edit-organization/src/lib/market-participant-edit-organization/master-data/dh-market-participant-organization-master-data.component.scss
  libs/dh/shared/domain/src/lib/generated/v1/model/create-organization-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/organization-dto.ts
Labels: cla-signed

#1410 feat: market roles translations
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
Labels: cla-signed

#1414 feat(watt): expose method for clearing selection
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: cla-signed

#1415 feat(wholesale): use watt-description-list
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/shared/ui-date-time/src/index.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/consumption-per-energy-supplier.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/consumption-per-energy-supplier.component.scss
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/consumption-per-energy-supplier.component.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/meta-data.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.scss
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.ts
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.html
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.scss
  libs/dh/wholesale/feature-search/src/lib/batch-details/dh-wholesale-batch-details.component.ts
  libs/ui-watt/src/lib/components/description-list/watt-description-list.component.scss
Labels: cla-signed

#1412 Moved button out of top component
  libs/ui-watt/src/lib/components/drawer/watt-drawer-topbar.component.scss
  libs/ui-watt/src/lib/components/drawer/watt-drawer-topbar.component.ts
  libs/ui-watt/src/lib/components/drawer/watt-drawer.component.html
  libs/ui-watt/src/lib/components/drawer/watt-drawer.component.scss
  libs/ui-watt/src/lib/components/drawer/watt-drawer.component.ts
Labels: cla-signed

#1416 fix(wholesale): make sure processStepResults won't emit undefined values
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/meta-data.ts
Labels: cla-signed

#1417 Refactor/wholesale clean up
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/consumption-per-energy-supplier.component.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/meta-data.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/steps/production-per-gridarea.component.ts
Labels: cla-signed

#1421 Add PermissionDetails instead of SelectablePermission
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserRoleController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  apps/dh/api-dh/source/DataHub.WebApi/Registration/DomainRegistrationExtensions.cs
  libs/dh/admin/data-access-api/src/lib/dh-admin-create-user-role-management-data-access-api.store.ts
  libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab-table.component.ts
  libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.ts
  libs/dh/admin/feature-create-user-role/src/lib/tabs/dh-create-userrole-tabs.component.ts
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/roles/tabs/content/dh-role-permissions.component.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-user-role-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/permission-details-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/user-role-with-permissions-dto.ts
Labels: cla-signed

#1425 feat(wholesale): add grid area code for settlement reports
  libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.html
Labels: cla-signed

#1427 fix(wholesale): default sorting of settlement reports
  libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.html
Labels: cla-signed

#1426 fix: Auth not required in BFF.
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantUserController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/TokenController.cs
  apps/dh/api-dh/source/DataHub.WebApi/Startup.cs
Labels: cla-signed

#1428 feat(wholesale): add calculation step for non-profiled consumption per balance responsible
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html
Labels: cla-signed

#1420 Feature/1027 invite user part 4
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantController.cs
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-actors-data-access-api.store.ts
  libs/dh/admin/feature-invite-user-modal/.eslintrc.json
  libs/dh/admin/feature-invite-user-modal/README.md
  libs/dh/admin/feature-invite-user-modal/jest.config.ts
  libs/dh/admin/feature-invite-user-modal/project.json
  libs/dh/admin/feature-invite-user-modal/src/index.ts
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.html
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.scss
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.ts
  libs/dh/admin/feature-invite-user-modal/src/test-setup.ts
  libs/dh/admin/feature-invite-user-modal/tsconfig.json
  libs/dh/admin/feature-invite-user-modal/tsconfig.lib.json
  libs/dh/admin/feature-invite-user-modal/tsconfig.spec.json
  libs/dh/admin/feature-user-management/src/lib/tabs/users-tab/dh-users-tab.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-http.service.ts
  libs/ui-watt/src/lib/foundations/typography/_typography.import.scss
  tsconfig.base.json
  workspace.json
Labels: cla-signed

#1430 Feature/1027 invite user part 6
  libs/dh/admin/feature-user-management/src/lib/drawer/dh-edit-user-modal/dh-edit-user-modal.component.ts
  libs/dh/admin/feature-user-management/src/lib/drawer/tabs/dh-drawer-tabs.component.ts
  libs/dh/admin/feature-user-roles/.eslintrc.json
  libs/dh/admin/feature-user-roles/README.md
  libs/dh/admin/feature-user-roles/jest.config.ts
  libs/dh/admin/feature-user-roles/project.json
  libs/dh/admin/feature-user-roles/src/index.ts
  libs/dh/admin/feature-user-roles/src/lib/dh-join-market-roles.pipe.ts
  libs/dh/admin/feature-user-roles/src/lib/dh-user-roles.component.html
  libs/dh/admin/feature-user-roles/src/lib/dh-user-roles.component.scss
  libs/dh/admin/feature-user-roles/src/lib/dh-user-roles.component.ts
  libs/dh/admin/feature-user-roles/src/lib/du-user-roles.component.spec.ts
  libs/dh/admin/feature-user-roles/src/test-setup.ts
  libs/dh/admin/feature-user-roles/tsconfig.json
  libs/dh/admin/feature-user-roles/tsconfig.lib.json
  libs/dh/admin/feature-user-roles/tsconfig.spec.json
  libs/dh/shared/feature-flags/src/lib/feature-flags.ts
  tsconfig.base.json
  workspace.json
Labels: cla-signed

#1424 refactor(style): adjust icon datepicker to not clip text
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/input/_datepicker.scss
  libs/ui-watt/src/lib/components/input/datepicker/watt-datepicker.component.html
  libs/ui-watt/src/lib/components/input/timepicker/watt-timepicker.component.html
Labels: ⚡ Watt, cla-signed

#1433 Set line length 100
  .editorconfig
Labels: cla-signed

#1432 Apply required GitHub changes
  .github/workflows/eo-cd.yml
Labels: cla-signed

#1434 html should also be allowed to be 100 chars
  .editorconfig
Labels: cla-signed

#1436 Changed heading color to match figma
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/card/watt-card-title.component.ts
  libs/ui-watt/src/lib/components/modal/watt-modal.component.scss
Labels: cla-signed

#1435 Added variant, with solid and elevation
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/card/watt-card.component.ts
  libs/ui-watt/src/lib/components/card/watt-card.stories.ts
Labels: cla-signed

#1437 Feature/1027 invite user part 7
  libs/dh/admin/data-access-api/src/index.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-assignable-user-roles.store.ts
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-assignable-user-roles/dh-assignable-user-roles.component.html
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-assignable-user-roles/dh-assignable-user-roles.component.scss
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-assignable-user-roles/dh-assignable-user-roles.component.ts
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.html
  libs/dh/admin/feature-invite-user-modal/src/lib/dh-invite-user-modal.component.ts
  libs/dh/admin/feature-user-roles/src/lib/dh-user-roles.component.ts
Labels: cla-signed

#1431 feat(watt): add support for setting initially selected rows on table
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/src/lib/components/table/+storybook/watt-table.stories.ts
  libs/ui-watt/src/lib/components/table/watt-table.component.spec.ts
  libs/ui-watt/src/lib/components/table/watt-table.component.ts
Labels: 🏗️ Platform, ⚡ Watt, cla-signed

#1439 chore: specify list of Nx generators
  .vscode/settings.json
Labels: cla-signed

#1440 refactor(dh): move permissions table component to its own library
  libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.html
  libs/dh/admin/feature-create-user-role/src/lib/tabs/create-role-permissions-tab/dh-create-userrole-permissions-tab.component.ts
  libs/dh/admin/ui-permissions-table/.eslintrc.json
  libs/dh/admin/ui-permissions-table/README.md
  libs/dh/admin/ui-permissions-table/jest.config.ts
  libs/dh/admin/ui-permissions-table/project.json
  libs/dh/admin/ui-permissions-table/src/index.ts
  libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.html
  libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.ts
  libs/dh/admin/ui-permissions-table/src/test-setup.ts
  libs/dh/admin/ui-permissions-table/tsconfig.json
  libs/dh/admin/ui-permissions-table/tsconfig.lib.json
  libs/dh/admin/ui-permissions-table/tsconfig.spec.json
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  tsconfig.base.json
  workspace.json
Labels: cla-signed

#1445 bump versions on watt changes
  .github/actions/yaml-increment-version/action.yaml
  .github/workflows/eo-cd.yml
Labels: cla-signed

#1333 feat(ui-watt): align checkbox with figma
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/ui-watt/.storybook/main.js
  libs/ui-watt/src/lib/components/checkbox/+storybook/storybook-checkbox-states.component.html
  libs/ui-watt/src/lib/components/checkbox/+storybook/storybook-checkbox-states.component.scss
  libs/ui-watt/src/lib/components/checkbox/+storybook/storybook-checkbox-states.component.ts
  libs/ui-watt/src/lib/components/checkbox/+storybook/storybook-checkbox-states.module.ts
  libs/ui-watt/src/lib/components/checkbox/+storybook/storybook-checkbox-states.stories.ts
  package.json
  yarn.lock
Labels: ⚡ Watt, cla-signed

#1441 feat: settlement report page - bff get filtered actors with gridarea code
  apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/Controllers/MarketParticipantControllerTests.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipant/Dto/FilteredActorDto.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/MarketParticipantController.cs
  libs/dh/admin/data-access-api/src/lib/dh-admin-user-actors-data-access-api.store.ts
  libs/dh/shared/domain/src/lib/generated/v1/api/market-participant-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/filtered-actor-dto.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
Labels: cla-signed

#1449 refactor(dh): move request for getting market role permissions to separate store
  libs/dh/admin/data-access-api/src/index.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-create-user-role-management-data-access-api.store.ts
  libs/dh/admin/data-access-api/src/lib/dh-admin-market-role-permissions.store.ts
  libs/dh/admin/feature-create-user-role/src/lib/tabs/dh-create-userrole-tabs.component.ts
Labels: cla-signed

#1422 Bugfix: Introduce timezone to api calls
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/consumption-page/shell/src/lib/eo-consumption.service.ts
  libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts
  libs/eo/production/shell/src/lib/eo-production.service.ts
  libs/eo/shared/services/src/app-settings/app-settings.store.ts
Labels: cla-signed

#1454 bugfix wrong time end
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts
Labels: cla-signed

#1452 Test
  .github/actions/yaml-increment-version/action.yaml
  .github/workflows/eo-cd.yml
Labels: cla-signed

#1453 feat: Search batch by period, state and grid areas.
  apps/dh/api-dh/source/DataHub.WebApi.Tests/Integration/Controllers/WholesaleControllerTests.cs
  apps/dh/api-dh/source/DataHub.WebApi/Controllers/WholesaleBatchController.cs
  apps/dh/api-dh/source/DataHub.WebApi/DataHub.WebApi.csproj
  libs/dh/shared/domain/src/lib/generated/v1/api/wholesale-batch-http.service.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/batch-search-dto-v2.ts
  libs/dh/shared/domain/src/lib/generated/v1/model/models.ts
  libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts
  libs/dh/wholesale/feature-search/src/lib/dh-wholesale-search.component.ts
  libs/dh/wholesale/feature-search/src/lib/form/dh-wholesale-form.component.ts
Labels: cla-signed

#1455 Feat/wholesale 787
  apps/dh/app-dh/project.json
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/wholesale.ts
  libs/dh/wholesale/data-access-api/src/lib/dh-wholesale-data-access-api.store.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/actors/dh-wholesale-actors.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/actors/dh-wholesale-actors.component.scss
  libs/dh/wholesale/feature-calculation-steps/src/lib/actors/dh-wholesale-actors.component.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/dh-wholesale-calculation-steps.component.ts
  libs/dh/wholesale/feature-calculation-steps/src/lib/time-series-points/dh-wholesale-time-series-points.component.html
  libs/dh/wholesale/feature-calculation-steps/src/lib/time-series-points/dh-wholesale-time-series-points.component.scss
  libs/dh/wholesale/feature-calculation-steps/src/lib/time-series-points/dh-wholesale-time-series-points.component.ts
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.html
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.scss
  libs/dh/wholesale/feature-search/src/lib/grid-areas/dh-wholesale-grid-areas.component.ts
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.html
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.scss
  libs/dh/wholesale/feature-search/src/lib/table/dh-wholesale-table.component.ts
  libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.html
  libs/dh/wholesale/feature-settlement-reports/src/lib/table/dh-wholesale-table.component.ts
  libs/ui-watt/src/lib/components/paginator/watt-paginator.component.ts
  libs/ui-watt/src/lib/components/table/+storybook/storybook-table-decorator.component.ts
  libs/ui-watt/src/lib/components/table/watt-table-data-source.ts
Labels: cla-signed

#1419 add dh orchestration
  .github/workflows/ci-orchestrator.yml
  .github/workflows/detect-changes.yml
  .github/workflows/dh-cd.yml
  .github/workflows/dh-ci-dotnet.yml
  .github/workflows/dh-ci-frontend.yml
  .github/workflows/watt-cd.yml
  .github/workflows/watt-ci-frontend.yml
  .github/workflows/watt-detect-changes.yml
Labels: cla-signed

#1458 Bugfix/wrong time end
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts
  libs/eo/shared/services/src/app-settings/app-settings.store.ts
Labels: cla-signed

#1456 feat(dh): add permissions table to edit user role modal
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/globalization/assets-localization/src/assets/i18n/da.json
  libs/dh/globalization/assets-localization/src/assets/i18n/en.json
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRolePermissions.json
  libs/dh/shared/data-access-msw/src/lib/mocks/marketParticipantUserRole.ts
Labels: cla-signed

#1462 This fixes date generation for Safari
  build/infrastructure/eo/chart/Chart.yaml
  build/infrastructure/eo/chart/values.yaml
  libs/eo/emissions/shell/src/lib/eo-emissions.service.ts
  libs/eo/origin-of-energy/shell/src/lib/eo-origin-of-energy.service.ts
  libs/eo/shared/services/src/app-settings/app-settings.store.ts
Labels: cla-signed

#1463 Use v10 workflows
  .github/workflows/watt-cd.yml
Labels: cla-signed

#1465 chore: update T-001 URL
  README.md
  apps/dh/e2e-dh/src/integration/b2c.spec.ts
  docs/dh/datahub-bookmarks.html
Labels: cla-signed

#1464 feat(dh): add support for permissions selection in edit user role
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.html
  libs/dh/admin/feature-edit-user-role-modal/src/lib/dh-edit-user-role-modal.component.ts
  libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.html
  libs/dh/admin/ui-permissions-table/src/lib/dh-permissions-table.component.ts
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRoleGetUserRoleWithPermissions.json
  libs/dh/shared/data-access-msw/src/lib/mocks/data/marketParticipantUserRolePermissions.json
Labels: cla-signed
